SET @query_id = 1;

SELECT STATE, SUM(DURATION) AS Total_R,
  ROUND(
    100 * SUM(DURATION) /
    (SELECT SUM(DURATION)
     FROM INFORMATION_SCHEMA.PROFILING
     WHERE QUERY_ID = @query_id
    ), 2) AS Pct_R,
  COUNT(*) AS Calls,
  SUM(DURATION) / COUNT(*) AS "R/Call"
FROM INFORMATION_SCHEMA.PROFILING
WHERE QUERY_ID = @query_id
GROUP BY STATE
ORDER BY Total_R DESC;